### ISSUE TITLE
Cache metadata to avoid re-parsing

### ISSUE THREAD

**Issue by markshelton** [markshelton/thickshake#2]
Currently, the parser does not check what is already in the database before proceeding with parsing. While the database manager ensures that duplicate records are not entered into the database, the parser performs redundant operations which slow the system. Add a flag and function that checks the contents of the database against the metadata source file and removes records from the parsing queue if they are already present in the database. This will likely be managed in a new function called from "parse.parse_records".

**Comment by JoshuaHollick** [comment]
How long does it take to ingest all the metadata currently? Unless it is a significant amount of time, it's probably not worth spending much time on this, especially if it's not introducing errors.

**Comment by markshelton** [comment]
Yep, agree that it's a low priority.
